build: Fix make rpm with VERSION_DM without dash
When building RPM from a branch based on a release tag the expected -git
suffix is missing breaking the script producing error like following one:

    error: line 215: Unterminated rich dependency: (2021-53.ge36b180a6.el9: Requires: device-mapper-devel >= 1.02.181 (2021-53.ge36b180a6.el9

(cherry picked from commit e60d7ce8e748cb6d51552879c162d01aafa17160)