device_id: Fix compiling when versionsort not found
alphasort was replaced with versionsort in 09e508cd438c755d293e4085ec584d87e7e7ea2e commit.

This commit fixes the following compiler error.

device/device_id.c:1608:65: error: use of undeclared identifier 'versionsort'
1608 |         sort_count = scandir(dirpath, &namelist, _filter_backup_files, versionsort);
     |                                                                        ^